server:
  port: 9999

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://octodream.chli7vzennox.ap-northeast-2.rds.amazonaws.com:3306/OctoDream?serverTimezone=Asia/Seoul
    username: admin
    password: OctoDream
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.39.126.140:8761/eureka

logging:
  level:
    com.example.com.example.userservice: DEBUG