-- =======================CREATE TABLE==========================
-- USER TABLE
CREATE TABLE `OctoDream`.`USER_TB` (
  `USER_PK` INT NOT NULL,
  `USER_EMAIL` VARCHAR(45) NOT NULL,
  `THUMBNAIL_IMAGE_URL` VARCHAR(200),
  `CHARACTER_NM` VARCHAR(45),
  `EXPERIENCE_VALUE` INT,
  `CHARACTER_IMAGE_URL` VARCHAR(200),
  PRIMARY KEY (`USER_PK`));


-- SLEEP TABLE 
CREATE TABLE `OctoDream`.`SLEEP_TB` (
  `SLEEP_PK` INT NOT NULL AUTO_INCREMENT,
  `USER_FK` INT NOT NULL,
  `SLEPT_TIME` DATETIME NOT NULL,
  `WAKEUP_TIME` DATETIME NOT NULL,
  `TOTAL_SLEEP_TIME` INT NOT NULL,
  PRIMARY KEY (`SLEEP_PK`));

-- RUNNING TABLE
CREATE TABLE `OctoDream`.`RUNNING_TB` (
  `RUNNING_PK` INT NOT NULL AUTO_INCREMENT,
  `USER_FK` INT NOT NULL,
  `RUNNING_TIME` DATETIME NOT NULL,
  `TOTAL_RUNNING_TIME` INT NOT NULL,
  `DISTANCE` INT NOT NULL,
  PRIMARY KEY (`RUNNING_PK`));

-- DIARY TABLE
CREATE TABLE `OctoDream`.`DIARY_TB` (
  `DIARY_PK` INT NOT NULL AUTO_INCREMENT,
  `USER_FK` INT NOT NULL,
  `CONTENT` VARCHAR(100) NOT NULL,
  `CREATED_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`DIARY_PK`));

-- GUESTBOOK_TABLE
CREATE TABLE `OctoDream`.`GUESTBOOK_TB` (
  `GUESTBOOK_PK` INT NOT NULL AUTO_INCREMENT,
  `USER_FK` INT NOT NULL,
  `GUEST_FK` INT NOT NULL,
  `CONTENT` VARCHAR(200) NOT NULL,
  `READ_FL` VARCHAR(45) NOT NULL,
  `CREATED_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`GUESTBOOK_PK`));


-- PAYMENT TABLE
CREATE TABLE `OctoDream`.`PAYMENT_TB` (
  `PAYMENT_PK` INT NOT NULL AUTO_INCREMENT,
  `USER_FK` INT NOT NULL,
  `ITEM_FK` INT NOT NULL,
  `AMOUNT` INT NOT NULL,
  `PAYMENT_TIME` VARCHAR(45) NOT NULL,
  `MERCHANT_UID` VARCHAR(100) NOT NULL,
  `IMP_UID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PAYMENT_PK`));

-- REFUND TABLE
CREATE TABLE `OctoDream`.`REFUND_TB` (
  `REFUND_PK` INT NOT NULL AUTO_INCREMENT,
  `PAYMENT_FK` INT NOT NULL,
  `REFUND_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`REFUND_PK`));

-- CHARACTER IMAGE TABLE 
CREATE TABLE `OctoDream`.`CHARACTER_IMAGE_TB` (
  `CHARACTER_IMAGE_PK` INT NOT NULL AUTO_INCREMENT,
  `CHARACTER_IMAGE_NM` VARCHAR(45) NOT NULL,
  `CHARACTER_IMAGE_URL` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CHARACTER_IMAGE_PK`));

-- COLLECTION TABLE
CREATE TABLE `OctoDream`.`COLLECTION_TB` (
  `COLLECTION_PK` INT NOT NULL AUTO_INCREMENT,
  `USER_FK` INT NOT NULL,
  `CHARACTER_IMAGE_FK` INT NOT NULL,
  PRIMARY KEY (`COLLECTION_PK`));

-- ITEM TABLE
CREATE TABLE `OctoDream`.`ITEM_TB` (
  `ITEM_PK` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `AMOUNT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ITEM_PK`));

-- REFRESH TOKEN
CREATE TABLE `OctoDream`.`REFRESH_TOKEN_TB` (
  `USER_FK` INT NOT NULL,
  `EXPIRATION_TIME` DATETIME NOT NULL,
  `REFRESH_TOKEN` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`USER_FK`));


-- =======================INSERT FORIGN KEY==========================
-- COLLECITON TB
alter table COLLECTION_TB add foreign key (USER_FK) references USER_TB (USER_PK);
alter table COLLECTION_TB add foreign key (CHARACTER_IMAGE_FK) references CHARACTER_IMAGE_TB (CHARACTER_IMAGE_PK);
-- DIARY TB
alter table DIARY_TB add foreign key (USER_FK) references USER_TB (USER_PK);
-- RUNNING TB
alter table RUNNING_TB add foreign key (USER_FK) references USER_TB (USER_PK);
-- SLEEP TB
alter table SLEEP_TB add foreign key (USER_FK) references USER_TB (USER_PK);
-- GUESTBOOK TB
alter table GUESTBOOK_TB add foreign key (USER_FK) references USER_TB (USER_PK);
alter table GUESTBOOK_TB add foreign key (GUEST_FK) references USER_TB (USER_PK);
-- PAYMENT TB
alter table PAYMENT_TB add foreign key (USER_FK) references USER_TB (USER_PK);
alter table PAYMENT_TB add foreign key (ITEM_FK) references ITEM_TB (ITEM_PK);
-- REFUND TB
alter table REFUND_TB add foreign key (PAYMENT_FK) references PAYMENT_TB (PAYMENT_PK);
-- REFRESH TOKEN TB
ALTER TABLE `OctoDream`.`REFRESH_TOKNE_TB` 
ADD CONSTRAINT `user_fk`
  FOREIGN KEY (`USER_FK`)
  REFERENCES `OctoDream`.`USER_TB` (`USER_PK`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

